/**
 * Re-exports from the auto-generated OpenAPI schema with readable aliases.
 *
 * DO NOT hand-edit the shape types here — they come from schema.ts which is
 * regenerated by `pnpm generate:api` whenever a Pydantic model changes.
 * Only aliases and convenience helpers belong in this file.
 *
 * Mapping strategy (resolves #98):
 *   Backend returns snake_case (FastAPI/Pydantic default).
 *   Frontend domain types (lib/types.ts) use camelCase + Spanish field names
 *   for historical reasons (e.g. `articulos`, `rango`, `publicada`).
 *   The transform functions in lib/api.ts bridge the two — they read backend
 *   shapes (this file) and produce frontend shapes (lib/types.ts).
 *   Adding a new field = edit the Pydantic model → run `pnpm generate:api`
 *   → TypeScript will error on the transform that reads the changed shape.
 *   No manual Backend* interface maintenance needed.
 */

import type { components } from './schema';

type S<K extends keyof components['schemas']> = components['schemas'][K];

// ─── Backend response shapes (replaces hand-written Backend* in lib/api.ts) ─

export type BackendLawSummary   = S<'LawSummary'>;
export type BackendLawMetadata  = S<'LawMetadata'>;
export type BackendLawDetail    = S<'LawDetail'>;
export type BackendLawVersion   = S<'LawVersion'>;
export type BackendLawDiff      = S<'LawDiff'>;
export type BackendDiffStats    = S<'DiffStats'>;
export type BackendArticle      = S<'Article'>;
export type BackendArticleResponse = S<'ArticleResponse'>;
export type BackendReference    = S<'Reference'>;
export type BackendSection      = S<'Section'>;
export type BackendSearchResponse = S<'SearchResponse'>;
export type BackendSearchResult = S<'SearchResult'>;
export type BackendGraphSubgraph = S<'GraphSubgraphResponse'>;
export type BackendGraphGlobal  = S<'GraphGlobalResponse'>;
export type BackendGraphNode    = S<'GraphNodeData'>;
export type BackendGraphEdge    = S<'GraphEdgeData'>;
export type BackendGraphStats   = S<'GraphStatsResponse'>;
export type BackendGraphTopItem = S<'GraphTopItem'>;
export type BackendModelInfo    = S<'ModelInfo'>;
export type BackendTagCount     = S<'TagCount'>;
export type BackendDashboard    = S<'DashboardPayload'>;
export type BackendDashboardSeries = S<'DashboardSeries'>;
export type BackendMetricCard   = S<'MetricCardPayload'>;
export type BackendPaginated<T> = {
  items: T[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
  has_next: boolean;
  has_previous: boolean;
};
export type BackendWarmupStatus = S<'WarmupStatusResponse'>;
export type BackendWhatsNewLaw  = S<'WhatsNewLaw'>;
export type BackendWhatsNewCorpus = S<'WhatsNewCorpus'>;
export type BackendWhatsNewResponse = S<'WhatsNewResponse'>;
export type BackendSystemProfile = S<'SystemProfileResponse'>;
