/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/laws/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full-text search across all laws
         * @description Search across all laws and articles for the given query string.
         */
        get: operations["search_laws_api_v1_laws_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * [Deprecated] Use /laws/search instead
         * @deprecated
         * @description Deprecated alias for ``/laws/search``.
         *
         *     Kept working through v1 so existing clients don't break, but flagged
         *     with a ``Deprecation: true`` header (RFC 8594 style) + a ``Link``
         *     pointing at the successor route. Remove at the v2 cut.
         */
        get: operations["search_laws_deprecated_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/laws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List laws with filtering and pagination
         * @description Return a paginated list of laws.  All filters are optional.
         */
        get: operations["list_laws_api_v1_laws_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/laws/{law_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full detail of a specific law
         * @description Return the complete parsed representation of a law.
         */
        get: operations["get_law_api_v1_laws__law_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/laws/{law_id}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all articles of a law
         * @description Return a paginated list of articles for the given law.
         *
         *     Sprint 7 api-13: pagination is computed in-memory by slicing the
         *     parsed ``law.articles`` list. That's fine while articles live in
         *     Markdown frontmatter (every law's article list fits comfortably in
         *     memory + ``total`` is always exact), but the day article storage
         *     moves to a database we'll want to push the OFFSET/LIMIT down to it.
         *     Flagging here so the migration touches this spot.
         */
        get: operations["list_articles_api_v1_laws__law_id__articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/laws/{law_id}/articles/{article_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific article by number
         * @description Return a single article by its number within a law.
         */
        get: operations["get_article_api_v1_laws__law_id__articles__article_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/laws/{law_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get version history of a law
         * @description Return git commit history for a law file, ordered newest-first.
         */
        get: operations["list_versions_api_v1_laws__law_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/laws/{law_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get diff between two versions of a law
         * @description Return the unified diff between two versions of a law.
         */
        get: operations["get_diff_api_v1_laws__law_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/neighbors/{law_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Neighbors
         * @description Return the direct successors (outgoing references) of a law node.
         */
        get: operations["get_neighbors_api_v1_graph_neighbors__law_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Path
         * @description Return the shortest directed path between two law nodes.
         *
         *     Query params use the `from` / `to` aliases (matches the convention of
         *     the versions diff endpoint and the documented example in the README).
         *
         *     Sprint 6 api-6: wraps the path list in an object so the response has
         *     room to carry metadata later (e.g. path length, intermediate hops).
         */
        get: operations["get_path_api_v1_graph_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/subgraph/{law_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subgraph
         * @description Return the ego-subgraph around a law node up to a given depth.
         *
         *     Returns 404 if the law id is not a node in the graph — `get_subgraph`
         *     on `LegalGraph` walks `successors`/`predecessors` which raise
         *     `NetworkXError` on unknown nodes; we want a controlled response.
         */
        get: operations["get_subgraph_api_v1_graph_subgraph__law_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Return high-level statistics about the knowledge graph.
         */
        get: operations["get_stats_api_v1_graph_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Top
         * @description Return the top-`limit` most referenced laws by PageRank.
         *
         *     Sprint 6 api-7 / rf-7: the `metric` query param used to exist but
         *     accepted only `pagerank` (single-value regex), and the handler
         *     discarded it with `del metric`. Dropped here until a second metric
         *     earns its place; the next ranking algorithm should re-introduce the
         *     param with a real `Literal["pagerank","betweenness",...]` shape.
         */
        get: operations["get_top_api_v1_graph_top_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every chat model the user can pick across all providers.
         * @description Return every available (provider, model) pair, flat.
         *
         *     Each provider is probed concurrently with a short timeout. Unreachable
         *     or unconfigured providers still appear in the response as a single
         *     placeholder entry (``configured: false``) so the UI can show them.
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Install an Ollama model and stream its progress via SSE (#119).
         * @description Trigger ``ollama pull <model>`` and stream the progress to the SPA.
         *
         *     Consumed by the model wizard's confirm step (#118). The wizard kicks the
         *     request, renders the byte counters as a progress bar, and treats the
         *     ``done`` event as "model is installed; re-detect to verify".
         */
        post: operations["pull_model_api_v1_models_pull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List chat threads, newest activity first.
         * @description Paginated list of threads ordered by ``updated_at`` desc.
         */
        get: operations["list_threads_api_v1_chat_threads_get"];
        put?: never;
        /**
         * Create a new chat thread.
         * @description Insert a new thread and return its read shape.
         */
        post: operations["create_thread_api_v1_chat_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a thread plus its full message history.
         * @description 404 if the id is unknown.
         */
        get: operations["get_thread_api_v1_chat_threads__thread_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a thread and all its messages (cascade). Idempotent.
         * @description Fully idempotent per RFC 7231 (Sprint 5 api-3): repeated calls
         *     converge on 204 regardless of whether the row existed. Cascade on
         *     ``ChatThread.messages`` cleans up child rows.
         */
        delete: operations["delete_thread_api_v1_chat_threads__thread_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename a thread (only ``title`` is patchable today).
         * @description Apply non-null fields from the body and return the updated row.
         *
         *     Sprint 6 api-9: an empty patch (every field None) used to silently
         *     succeed and bump ``updated_at`` — a no-op write that confused list
         *     ordering. Now refused with 400 so the client knows to stop sending
         *     empty bodies.
         */
        patch: operations["patch_thread_api_v1_chat_threads__thread_id__patch"];
        trace?: never;
    };
    "/api/v1/chat/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append one message to a thread. Streaming send lives in #84.
         * @description Append a turn, touch the thread's ``updated_at`` and return the
         *     persisted row. Intentionally non-streaming — see issue #84 for the
         *     SSE counterpart that adds the assistant + tool turns.
         *
         *     Sprint 6 api-5: emits ``Location: /api/v1/chat/threads/{thread_id}/
         *     messages/{message_id}`` per RFC 7231 for 201 responses. There is no
         *     GET endpoint for an individual message today (the SPA reads them
         *     nested under the thread), but the header is correct and lets a
         *     future client distinguish the new row from the thread's full list.
         */
        post: operations["append_message_api_v1_chat_threads__thread_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/threads/{thread_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream an assistant reply for the user message (SSE).
         * @description Persist the user turn, then stream the assistant reply as SSE.
         *
         *     Wire format (one event per record, blank line terminator):
         *
         *     ::
         *
         *         event: text
         *         data: {"delta": "Hola "}
         *
         *         event: text
         *         data: {"delta": "mundo."}
         *
         *         event: done
         *         data: {}
         *
         *     On provider error we emit ``event: error`` with a ``detail`` field
         *     before the final ``done``. Partial assistant replies are persisted —
         *     a dropped connection leaves the thread with whatever streamed
         *     through. See :mod:`lexflow.chat.streaming` for the generator.
         *
         *     The MCP tool-use loop (``tool_call`` / ``source`` events) is tracked
         *     as a follow-up issue; the wire format is forward-compatible so
         *     clients that already render those event types keep working.
         */
        post: operations["send_message_stream_api_v1_chat_threads__thread_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/{preset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated dashboard data (KPI cards + main series).
         * @description Return the KPI cards + main chart series for the requested preset.
         */
        get: operations["get_dashboard_api_v1_dashboards__preset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Corpus
         * @description Pull the latest legalize-es revision and refresh state.
         *
         *     Sprint 5 api-1: returns ``200 OK`` only for the ``noop`` mode (the
         *     corpus was already at HEAD). Modes that actually mutate state
         *     (``incremental``, ``rebuild``) return ``201 Created`` with a
         *     ``Location`` header pointing at the resulting revision. This lets
         *     cache-friendly clients tell "nothing happened" from "you changed the
         *     world" without parsing the body.
         *
         *     Returns a payload describing what happened: ``mode`` is ``noop``
         *     (nothing changed), ``incremental`` (a bounded delta was applied),
         *     or ``rebuild`` (caches dropped for a full rebuild on next use).
         */
        post: operations["sync_corpus_api_v1_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/warmup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Background warm-up progress for the SPA to poll on startup.
         * @description Return the current snapshot of background warm-up readiness.
         */
        get: operations["get_warmup_status_api_v1_system_warmup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/whats-new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What changed in the corpus since the given commit (#228).
         * @description Return a corpus diff between *since* and the current HEAD.
         *
         *     On first launch (``since`` absent) or when the diff is unavailable,
         *     returns empty lists — the SPA degrades to showing tips instead.
         */
        get: operations["get_whats_new_api_v1_system_whats_new_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Host hardware + local LLM providers, consumed by the model wizard (#117).
         * @description Return a one-shot snapshot of host capacity.
         *
         *     The wizard runs detection once during onboarding (and again only when
         *     the user explicitly relaunches it). Bounded at ~700 ms total because
         *     each local-provider probe is capped at 500 ms and they run
         *     concurrently.
         */
        get: operations["get_system_profile_api_v1_system_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tag vocabulary across the corpus, ranked by usage.
         * @description Return ``{items: [{tag, count}]}`` sorted by count desc, then tag asc.
         *
         *     Sprint 6 api-6: previously returned a bare list. Wrapped now so the
         *     contract has room to grow (e.g. total distinct tags, pagination).
         */
        get: operations["list_tags_api_v1_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all MCP servers (built-in + user-added).
         * @description Return the combined catalog, built-ins first.
         */
        get: operations["list_servers_api_v1_mcp_servers_get"];
        put?: never;
        /**
         * Add a user MCP server (Claude Desktop schema).
         * @description Append *body* to the user list and persist.
         *
         *     Rejects names that collide with a built-in (409) or with an
         *     existing user entry (409). Built-in entries are never editable
         *     via this endpoint — they're a code-defined catalog.
         */
        post: operations["create_server_api_v1_mcp_servers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a user MCP server. Idempotent.
         * @description Remove the user entry identified by *name*. Idempotent.
         *
         *     Built-in entries cannot be deleted (409). Missing user entries
         *     return 204 — the same response a successful delete returns, so
         *     clients retrying lost responses converge cleanly (Sprint 5 api-3
         *     convention).
         */
        delete: operations["delete_server_api_v1_mcp_servers__name__delete"];
        options?: never;
        head?: never;
        /**
         * Toggle the enabled flag on a user MCP server.
         * @description Apply patchable fields to the user entry identified by *name*.
         */
        patch: operations["patch_server_api_v1_mcp_servers__name__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Article
         * @description A single article within a law.
         */
        Article: {
            /**
             * Number
             * @description Article number (e.g. '1', '2 bis').
             */
            number: string;
            /**
             * Title
             * @description Optional article title.
             */
            title?: string | null;
            /**
             * Text
             * @description Full text content of the article.
             */
            text: string;
            /**
             * References
             * @description Cross-references found in this article.
             */
            references?: components["schemas"]["Reference"][];
        };
        /**
         * ArticleResponse
         * @description Single article response with parent law context.
         */
        ArticleResponse: {
            /** Law Id */
            law_id: string;
            /** Law Title */
            law_title: string;
            article: components["schemas"]["Article"];
        };
        /**
         * ChatMessageCreate
         * @description Body of ``POST /chat/threads/{id}/messages``.
         *
         *     Tracked here for completeness even though the actual streaming-send
         *     endpoint lands in #84 — the persistence layer needs a way to record
         *     user turns *now* so the rest of the surface (thread list with
         *     preview, etc.) becomes testable without waiting on the SSE work.
         */
        ChatMessageCreate: {
            /**
             * Role
             * @default user
             * @enum {string}
             */
            role: "user" | "assistant" | "tool" | "system";
            /** Content */
            content: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ChatMessageRead
         * @description One persisted message as returned to the client.
         *
         *     ``payload`` is the decoded ``payload_json`` from storage — assistant
         *     sources live under ``payload.sources``, tool calls under
         *     ``payload.name`` / ``payload.args`` / ``payload.result``.
         */
        ChatMessageRead: {
            /** Id */
            id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "tool" | "system";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ChatSendRequest
         * @description Body of ``POST /chat/threads/{id}/send`` (issue #84).
         *
         *     Carries the user message + the model id chosen for this turn. The
         *     model id follows the ``provider:model`` convention used by the
         *     ``/api/v1/models`` listing (e.g. ``"openai:gpt-4o"``).
         */
        ChatSendRequest: {
            /** Message */
            message: string;
            /** Model */
            model: string;
        };
        /**
         * ChatThreadCreate
         * @description Body of ``POST /chat/threads``. All fields optional.
         */
        ChatThreadCreate: {
            /** Title */
            title?: string | null;
            /** Model */
            model?: string | null;
        };
        /**
         * ChatThreadDetail
         * @description Thread + full message history (``GET /chat/threads/{id}``).
         */
        ChatThreadDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Model */
            model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Preview */
            preview?: string | null;
            /** Messages */
            messages?: components["schemas"]["ChatMessageRead"][];
        };
        /**
         * ChatThreadList
         * @description Paginated listing envelope for ``GET /chat/threads``.
         */
        ChatThreadList: {
            /** Items */
            items: components["schemas"]["ChatThreadRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * ChatThreadPatch
         * @description Body of ``PATCH /chat/threads/{id}``. Currently only ``title``.
         */
        ChatThreadPatch: {
            /** Title */
            title?: string | null;
        };
        /**
         * ChatThreadRead
         * @description Thread metadata returned in listings (no messages).
         */
        ChatThreadRead: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Model */
            model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Preview */
            preview?: string | null;
        };
        /**
         * ConsolidationStatus
         * @description Consolidation state from the BOE.
         * @enum {string}
         */
        ConsolidationStatus: "Finalizado" | "En curso" | "unknown";
        /**
         * DashboardPayload
         * @description Full response of ``GET /api/v1/dashboards/{preset}``.
         */
        DashboardPayload: {
            /** Preset */
            preset: string;
            /** Cards */
            cards: components["schemas"]["MetricCardPayload"][];
            series: components["schemas"]["DashboardSeries"];
        };
        /**
         * DashboardSeries
         * @description The main chart's data: parallel arrays + a recent highlight cut.
         */
        DashboardSeries: {
            /** Labels */
            labels: string[];
            /** Values */
            values: number[];
            /** Recent From */
            recent_from?: number | null;
        };
        /**
         * DiffStats
         * @description Statistics for a diff between two versions.
         */
        DiffStats: {
            /**
             * Additions
             * @default 0
             */
            additions: number;
            /**
             * Deletions
             * @default 0
             */
            deletions: number;
            /** Changed Articles */
            changed_articles?: string[];
        };
        /**
         * GraphEdgeData
         * @description Edge representation for subgraph responses.
         */
        GraphEdgeData: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Source Article */
            source_article?: string | null;
        };
        /**
         * GraphNeighborsResponse
         * @description Response for the graph neighbors endpoint.
         */
        GraphNeighborsResponse: {
            /** Law Id */
            law_id: string;
            /** Neighbors */
            neighbors: string[];
            /** Count */
            count: number;
        };
        /**
         * GraphNodeData
         * @description Node representation for subgraph responses.
         *
         *     ``community`` and ``pagerank`` (issue #143) are computed over the
         *     returned subgraph — not the global graph — so they stay meaningful
         *     as the seed/depth change. The frontend uses ``community`` to colour
         *     clusters and ``pagerank`` to size nodes.
         */
        GraphNodeData: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Rank */
            rank?: string | null;
            /** Status */
            status?: string | null;
            /** Community */
            community?: number | null;
            /** Pagerank */
            pagerank?: number | null;
        };
        /**
         * GraphPathResponse
         * @description Wrapper for ``GET /api/v1/graph/path`` (Sprint 6 api-6).
         */
        GraphPathResponse: {
            /** Path */
            path: string[];
        };
        /**
         * GraphStatsResponse
         * @description High-level statistics about the knowledge graph.
         */
        GraphStatsResponse: {
            /** Node Count */
            node_count: number;
            /** Edge Count */
            edge_count: number;
            /** Density */
            density: number;
            /** Weakly Connected Components */
            weakly_connected_components: number;
        };
        /**
         * GraphSubgraphResponse
         * @description Response for the subgraph endpoint.
         */
        GraphSubgraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNodeData"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeData"][];
        };
        /**
         * GraphTopItem
         * @description A law ranked by PageRank score.
         */
        GraphTopItem: {
            /** Law Id */
            law_id: string;
            /** Score */
            score: number;
            /** Title */
            title?: string | null;
        };
        /**
         * GraphTopResponse
         * @description Wrapper for ``GET /api/v1/graph/top`` (Sprint 6 api-6).
         *
         *     Top-level JSON arrays are a known design smell (JSON-hijacking risk
         *     in some clients, no room to grow metadata). Every list endpoint
         *     wraps its rows in an object with a single ``items`` key.
         */
        GraphTopResponse: {
            /** Items */
            items: components["schemas"]["GraphTopItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Jurisdiction
         * @description Jurisdiction codes for Spanish autonomous communities.
         *
         *     ``ES`` is the national (state) level; the rest are autonomous
         *     communities plus the autonomous cities of Ceuta and Melilla.
         * @enum {string}
         */
        Jurisdiction: "es" | "es-an" | "es-ar" | "es-as" | "es-cb" | "es-ce" | "es-cl" | "es-cm" | "es-cn" | "es-ct" | "es-ex" | "es-ga" | "es-ib" | "es-mc" | "es-md" | "es-ml" | "es-nc" | "es-pv" | "es-ri" | "es-vc";
        /**
         * LawDetail
         * @description Full law detail for the single-law endpoint.
         */
        LawDetail: {
            metadata: components["schemas"]["LawMetadata"];
            /** Sections */
            sections: components["schemas"]["Section"][];
            /** Articles */
            articles: components["schemas"]["Article"][];
            /** References */
            references: components["schemas"]["Reference"][];
            /** Article Count */
            article_count: number;
        };
        /**
         * LawDiff
         * @description Diff between two versions of a law.
         */
        LawDiff: {
            /** Law Id */
            law_id: string;
            /** From Commit */
            from_commit: string;
            /** To Commit */
            to_commit: string;
            /** From Date */
            from_date?: string | null;
            /** To Date */
            to_date?: string | null;
            /**
             * Diff Text
             * @description Unified diff output.
             */
            diff_text: string;
            stats: components["schemas"]["DiffStats"];
        };
        /**
         * LawMetadata
         * @description Metadata extracted from YAML frontmatter of a legalize-es file.
         */
        LawMetadata: {
            /**
             * Identifier
             * @description BOE identifier (e.g. 'BOE-A-1978-31229').
             */
            identifier: string;
            /**
             * Title
             * @description Full official title of the law.
             */
            title: string;
            /**
             * @description Hierarchical rank.
             * @default otro
             */
            rank: components["schemas"]["LawRank"];
            /** @default in_force */
            status: components["schemas"]["LawStatus"];
            /** Publication Date */
            publication_date?: string | null;
            /** Enactment Date */
            enactment_date?: string | null;
            /** Last Updated */
            last_updated?: string | null;
            /**
             * Source
             * @description URL to official BOE source.
             */
            source?: string | null;
            /** Department */
            department?: string | null;
            /** Official Journal */
            official_journal?: string | null;
            /** Journal Issue */
            journal_issue?: string | null;
            /** @default unknown */
            consolidation_status: components["schemas"]["ConsolidationStatus"];
            /** @default Estatal */
            scope: components["schemas"]["Scope"];
            jurisdiction?: components["schemas"]["Jurisdiction"] | null;
            /**
             * Country
             * @default es
             */
            country: string;
            /**
             * Tags
             * @description Normalised topic tags.
             */
            tags?: string[];
            /**
             * Category
             * @description Primary category, if the source declares one.
             */
            category?: string | null;
        };
        /**
         * LawRank
         * @description Hierarchical rank of a legal norm.
         *
         *     Values match the raw ``rank`` field in legalize-es YAML frontmatter.
         * @enum {string}
         */
        LawRank: "ley" | "ley_organica" | "real_decreto" | "real_decreto_ley" | "real_decreto_legislativo" | "decreto_legislativo" | "orden" | "otro";
        /**
         * LawStatus
         * @description Current enforcement status of a legal norm.
         * @enum {string}
         */
        LawStatus: "in_force" | "repealed" | "partially_repealed" | "pending";
        /**
         * LawSummary
         * @description Lightweight law representation for list endpoints.
         */
        LawSummary: {
            /** Identifier */
            identifier: string;
            /** Title */
            title: string;
            rank: components["schemas"]["LawRank"];
            status: components["schemas"]["LawStatus"];
            /** Publication Date */
            publication_date: string | null;
            /** Article Count */
            article_count: number;
            scope: components["schemas"]["Scope"];
            /** Jurisdiction */
            jurisdiction: string | null;
        };
        /**
         * LawVersion
         * @description A historical version of a law, derived from git commit history.
         */
        LawVersion: {
            /** Commit Hash */
            commit_hash: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Message */
            message: string;
            /**
             * Norma
             * @description Reform norm from git trailer.
             */
            norma?: string | null;
            /**
             * Disposicion
             * @description Amending disposition identifier.
             */
            disposicion?: string | null;
            /**
             * Articulos Afectados
             * @description List of affected article identifiers.
             */
            articulos_afectados?: string[];
        };
        /**
         * McpServerCommand
         * @description One MCP server launch command — matches the Claude Desktop schema.
         *
         *     A server can either be launched as a child process (``command`` +
         *     ``args``) or referenced by URL (``url``); the wire protocol covers
         *     both styles and we keep both fields so a paste from Claude Desktop's
         *     ``claude_desktop_config.json`` round-trips losslessly.
         */
        McpServerCommand: {
            /**
             * Command
             * @description Executable to launch (e.g. 'npx', 'uvx', '/usr/local/bin/foo').
             */
            command?: string | null;
            /**
             * Args
             * @description Args passed to the command. Each entry capped at 512 chars.
             */
            args?: string[];
            /**
             * Env
             * @description Extra env vars passed to the child process.
             */
            env?: {
                [key: string]: string;
            };
            /**
             * Url
             * @description Remote MCP endpoint (mutually exclusive with command).
             */
            url?: string | null;
        };
        /**
         * McpServerCreateRequest
         * @description Body for ``POST /api/v1/mcp/servers`` — adds a user entry.
         *
         *     Reuses the user-entry shape; the server-side handler refuses names
         *     that collide with built-in entries.
         */
        McpServerCreateRequest: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            command: components["schemas"]["McpServerCommand"];
        };
        /**
         * McpServerListResponse
         * @description Wrapper for ``GET /api/v1/mcp/servers`` (Sprint 6 api-6 convention).
         *
         *     Wrapped instead of returning a bare list so we can grow metadata
         *     (counts, schema version, last-modified) without breaking clients.
         */
        McpServerListResponse: {
            /** Items */
            items: components["schemas"]["McpServerView"][];
        };
        /**
         * McpServerPatchRequest
         * @description Body for ``PATCH /api/v1/mcp/servers/{name}``.
         *
         *     Only ``enabled`` is patchable today; renaming a server is a delete +
         *     add because the name is the key.
         */
        McpServerPatchRequest: {
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * McpServerView
         * @description Flat shape returned by ``GET /api/v1/mcp/servers``.
         *
         *     ``kind`` is the discriminator the SPA branches on. Built-in rows
         *     carry ``enabled: true`` purely for symmetry — the SPA refuses to
         *     flip them locally (the field is informational).
         */
        McpServerView: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            command: components["schemas"]["McpServerCommand"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "builtin" | "user";
            /** Enabled */
            enabled: boolean;
            /** Docs Url */
            docs_url?: string | null;
        };
        /**
         * MetricCardPayload
         * @description Single KPI tile rendered above the main chart on the SPA.
         */
        MetricCardPayload: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Value */
            value: string;
            /** Delta */
            delta: string;
            /** Spark */
            spark?: number[];
            /** Positive */
            positive?: boolean | null;
        };
        /**
         * ModelInfo
         * @description Single (provider, model) pair surfaced by ``GET /api/v1/models``.
         *
         *     Invariants:
         *     * ``id`` is the unique key the frontend uses to identify a model. Always
         *       ``"{provider}:{model}"`` for configured entries, or ``"{provider}:"``
         *       for unconfigured-provider placeholders.
         *     * ``configured = False`` means the user has not set up this provider
         *       (e.g. no API key for a cloud one, or the local server isn't running).
         *       In that case ``model`` is the empty string and the entry is a
         *       placeholder so the UI can show "OpenAI — needs API key".
         */
        ModelInfo: {
            /**
             * Id
             * @description Stable identifier, e.g. "ollama:llama3.1:8b".
             */
            id: string;
            /**
             * Provider
             * @description Provider key: ollama | lmstudio | openai | anthropic | google.
             */
            provider: string;
            /**
             * Model
             * @description Model name within the provider. Empty when the provider is not configured.
             * @default
             */
            model: string;
            /**
             * Local
             * @description True for Ollama / LM Studio; False for cloud providers.
             */
            local: boolean;
            /**
             * Configured
             * @description True when the provider is reachable and a model is available.
             */
            configured: boolean;
            /**
             * Context Window
             * @description Best-effort context window in tokens. None when unknown.
             */
            context_window?: number | null;
            /**
             * Error
             * @description Short error message when configured=False.
             */
            error?: string | null;
        };
        /**
         * ModelPullRequest
         * @description Body for ``POST /api/v1/models/pull``.
         */
        ModelPullRequest: {
            /**
             * Model
             * @description Ollama model tag, e.g. ``qwen2.5:7b`` or ``llama3.2``.
             */
            model: string;
        };
        /** PaginatedResponse[Article] */
        PaginatedResponse_Article_: {
            /** Items */
            items: components["schemas"]["Article"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Total Pages
             * @description Total number of pages.
             */
            readonly total_pages: number;
            /**
             * Has Next
             * @description Whether there is a next page.
             */
            readonly has_next: boolean;
            /**
             * Has Previous
             * @description Whether there is a previous page.
             */
            readonly has_previous: boolean;
        };
        /** PaginatedResponse[LawSummary] */
        PaginatedResponse_LawSummary_: {
            /** Items */
            items: components["schemas"]["LawSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Total Pages
             * @description Total number of pages.
             */
            readonly total_pages: number;
            /**
             * Has Next
             * @description Whether there is a next page.
             */
            readonly has_next: boolean;
            /**
             * Has Previous
             * @description Whether there is a previous page.
             */
            readonly has_previous: boolean;
        };
        /**
         * Reference
         * @description A cross-reference from one law or article to another.
         */
        Reference: {
            /**
             * Target Id
             * @description BOE identifier of the referenced law, if resolvable.
             */
            target_id?: string | null;
            /**
             * Target Text
             * @description Raw text of the reference as found in the source.
             */
            target_text: string;
            /**
             * Source Article
             * @description Article number where this reference appears.
             */
            source_article?: string | null;
        };
        /**
         * Scope
         * @description Territorial scope of a legal norm.
         * @enum {string}
         */
        Scope: "Estatal" | "Autonómico" | "Local";
        /**
         * SearchResponse
         * @description Search results wrapper.
         */
        SearchResponse: {
            /** Query */
            query: string;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["SearchResult"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * SearchResult
         * @description A single search hit.
         *
         *     ``match_start`` / ``match_end`` are character offsets within ``snippet``
         *     (not the source text) pointing at the substring the frontend should
         *     visually highlight. ``None`` when the snippet had to be returned
         *     without an explicit match anchor — e.g. the query lay outside the
         *     trimmed window or the snippet was synthesised from a title-only match.
         */
        SearchResult: {
            /** Law Id */
            law_id: string;
            /** Law Title */
            law_title: string;
            /** Article Number */
            article_number: string | null;
            /**
             * Snippet
             * @description Text fragment with match context.
             */
            snippet: string;
            /**
             * Match Start
             * @description Start offset of the match within ``snippet`` (inclusive). Null when not locatable.
             */
            match_start?: number | null;
            /**
             * Match End
             * @description Exclusive end offset of the match within ``snippet``. Null when not locatable.
             */
            match_end?: number | null;
            /** Score */
            score: number;
        };
        /**
         * Section
         * @description A structural section (Titulo, Capitulo, Seccion) within a law.
         *
         *     Sections nest recursively to model the heading hierarchy.
         */
        Section: {
            /**
             * Level
             * @description Heading depth: 1=document, 2=Titulo, 3=Capitulo, 4=Seccion, 5=Articulo.
             */
            level: number;
            /**
             * Heading
             * @description Section heading text.
             */
            heading: string;
            /** Articles */
            articles?: components["schemas"]["Article"][];
            /** Subsections */
            subsections?: components["schemas"]["Section"][];
        };
        /**
         * SystemProfileResponse
         * @description Hardware + local-provider snapshot consumed by the model wizard (#117/#118).
         *
         *     Numbers are point-in-time and meant for one-shot wizard logic — the
         *     frontend should not poll this endpoint. The wizard re-runs detection
         *     only when the user explicitly relaunches it from Ajustes → Modelos.
         */
        SystemProfileResponse: {
            /**
             * Total Ram Gb
             * @description Total physical RAM in GiB.
             */
            total_ram_gb: number;
            /**
             * Available Ram Gb
             * @description Free RAM at probe time, GiB.
             */
            available_ram_gb: number;
            /**
             * Cpu Cores
             * @description Logical CPU count (hyperthreads included).
             */
            cpu_cores: number;
            /**
             * Has Nvidia Gpu
             * @description Whether NVML reported at least one NVIDIA GPU.
             */
            has_nvidia_gpu: boolean;
            /**
             * Vram Gb
             * @description VRAM of the first NVIDIA GPU in GiB, or null if no GPU is present.
             */
            vram_gb?: number | null;
            /**
             * Gpu Name
             * @description Marketing name of the first NVIDIA GPU (e.g. 'NVIDIA GeForce RTX 4070').
             */
            gpu_name?: string | null;
            /**
             * Is Apple Silicon
             * @description True on ARM64 macOS so the wizard can recommend MLX/unified-memory tiers.
             */
            is_apple_silicon: boolean;
            /**
             * Platform
             * @description Short OS label: 'linux', 'darwin' or 'windows'.
             */
            platform: string;
            /**
             * Ollama Running
             * @description Whether Ollama responded on http://127.0.0.1:11434.
             */
            ollama_running: boolean;
            /**
             * Ollama Models
             * @description Model tags currently installed in Ollama (empty when Ollama is not running).
             */
            ollama_models?: string[];
            /**
             * Lmstudio Running
             * @description Whether LM Studio responded on http://127.0.0.1:1234.
             */
            lmstudio_running: boolean;
        };
        /**
         * TagCount
         * @description A normalised tag and how many laws carry it.
         */
        TagCount: {
            /**
             * Tag
             * @description Normalised kebab-case tag slug.
             */
            tag: string;
            /**
             * Count
             * @description Number of laws tagged with it.
             */
            count: number;
        };
        /**
         * TagsResponse
         * @description Wrapper for ``GET /api/v1/tags`` (Sprint 6 api-6).
         */
        TagsResponse: {
            /** Items */
            items: components["schemas"]["TagCount"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarmupStatusResponse
         * @description Snapshot of the post-startup background warm-up (#222).
         *
         *     Polled by the SPA every 2-3 s until ``ready`` flips to true so the
         *     UI can show specific "still loading X" messages instead of the
         *     generic spinner.
         */
        WarmupStatusResponse: {
            /**
             * Ready
             * @description All warm-up stages complete.
             */
            ready: boolean;
            /**
             * Metadata Ready
             * @description Frontmatter preload finished.
             */
            metadata_ready: boolean;
            /**
             * Search Ready
             * @description In-memory search index built.
             */
            search_ready: boolean;
            /**
             * Graph Ready
             * @description Knowledge graph loaded/rebuilt.
             */
            graph_ready: boolean;
            /**
             * Error
             * @description Last warm-up error message, if any stage failed (the other stages can still report ready).
             */
            error?: string | null;
            /**
             * Durations Seconds
             * @description Wall-clock seconds spent in each completed stage. Useful for triage.
             */
            durations_seconds?: {
                [key: string]: number;
            };
        };
        /**
         * WhatsNewCorpus
         * @description Corpus diff summary for the what's-new splash panel (#228).
         */
        WhatsNewCorpus: {
            /** From Commit */
            from_commit?: string | null;
            /** To Commit */
            to_commit?: string | null;
            /** Added */
            added?: components["schemas"]["WhatsNewLaw"][];
            /** Modified */
            modified?: components["schemas"]["WhatsNewLaw"][];
            /** Removed */
            removed?: string[];
        };
        /**
         * WhatsNewLaw
         * @description A law that changed between two corpus revisions.
         */
        WhatsNewLaw: {
            /** Law Id */
            law_id: string;
            /** Title */
            title?: string | null;
        };
        /**
         * WhatsNewResponse
         * @description Response for GET /system/whats-new — what changed since last launch (#228).
         */
        WhatsNewResponse: {
            corpus: components["schemas"]["WhatsNewCorpus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_laws_api_v1_laws_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_laws_deprecated_api_v1_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_laws_api_v1_laws_get: {
        parameters: {
            query?: {
                /** @description Filter by law rank */
                rank?: components["schemas"]["LawRank"] | null;
                /** @description Filter by enforcement status */
                status?: components["schemas"]["LawStatus"] | null;
                /** @description Filter by territorial scope */
                scope?: components["schemas"]["Scope"] | null;
                /** @description Filter by jurisdiction code (e.g. es-md) */
                jurisdiction?: string | null;
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_LawSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_law_api_v1_laws__law_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_api_v1_laws__law_id__articles_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path: {
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Article_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_api_v1_laws__law_id__articles__article_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                law_id: string;
                article_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_v1_laws__law_id__versions_get: {
        parameters: {
            query?: {
                /** @description Maximum versions to return */
                max_count?: number;
            };
            header?: never;
            path: {
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diff_api_v1_laws__law_id__diff_get: {
        parameters: {
            query: {
                /** @description Source commit hash (7-40 hex chars) */
                from: string;
                /** @description Target commit hash (7-40 hex chars) */
                to: string;
            };
            header?: never;
            path: {
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawDiff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neighbors_api_v1_graph_neighbors__law_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphNeighborsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_path_api_v1_graph_path_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subgraph_api_v1_graph_subgraph__law_id__get: {
        parameters: {
            query?: {
                depth?: number;
            };
            header?: never;
            path: {
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphSubgraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_v1_graph_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphStatsResponse"];
                };
            };
        };
    };
    get_top_api_v1_graph_top_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphTopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
        };
    };
    pull_model_api_v1_models_pull_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelPullRequest"];
            };
        };
        responses: {
            /** @description Server-sent events stream with progress / done / error. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Model tag failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_threads_api_v1_chat_threads_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_thread_api_v1_chat_threads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatThreadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_api_v1_chat_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_api_v1_chat_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_thread_api_v1_chat_threads__thread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatThreadPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatThreadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_message_api_v1_chat_threads__thread_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_stream_api_v1_chat_threads__thread_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSendRequest"];
            };
        };
        responses: {
            /** @description Server-sent events stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Thread not found — emitted BEFORE the stream opens. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_dashboards__preset__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset: "compliance" | "analytics";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_corpus_api_v1_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | number;
                    };
                };
            };
        };
    };
    get_warmup_status_api_v1_system_warmup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarmupStatusResponse"];
                };
            };
        };
    };
    get_whats_new_api_v1_system_whats_new_get: {
        parameters: {
            query?: {
                /** @description Commit hash of the last corpus revision seen by the client (stored in localStorage). Omit or pass null on first launch. */
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsNewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_profile_api_v1_system_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemProfileResponse"];
                };
            };
        };
    };
    list_tags_api_v1_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsResponse"];
                };
            };
        };
    };
    list_servers_api_v1_mcp_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerListResponse"];
                };
            };
        };
    };
    create_server_api_v1_mcp_servers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpServerCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_server_api_v1_mcp_servers__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_server_api_v1_mcp_servers__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpServerPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
